spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:mariadb://localhost/greenroom
    username: root
    password: ENC(XYnmOTbvyFIoJ3A/PTVR5Q==)
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode : never
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(GoXmhnlYhTWXrVx550csmitTvIcQWnfoqSorlY2jWfk=)
    password: ENC(dXbTFoOHJHLNxADWJ26ejY77pDpr0E/B3CYtujkuV7g=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password:  123456
  data:
    elasticsearch:
      repositories:
        enabled: true
cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: ENC(xUQajnpokjuZq6SkK/+p3PbfgNQM/yxwqAb/jU3aPZk=)
      secret-key: ENC(FJ9UEHzhaVXzPeI0D4Ja99GYuFy4/riHuu9+S/e1zqgOS1ZmxsEf7j3OMFcSit1yhhAPvuw/4vA=)
    s3:
      bucket: ENC(HUCZanm+kg08GwIHJ9fzr1bHr6M0skCGAZJgRXGSPC4=)
      path:
        root: ENC(eBnxQq5PqbXeyZ73q30lhL40qXHlr46R5XbHnfgzZM+7NU6LQxoMevHgOP37yWp+)
  cdn:
    path:
      root: ENC(VzfXK3IN7tLoueO7y0qdFvjl1CYogxmul6Dvd2uOnSq9x4Yie3FOUQk3xGbZLKLM)
  image:
    path:
      user: local/user
      plant : plant
      greenroom: local/greenroom
temp:
  filePath: src/main/resources/
logging.level:
  #  org.hibernate.SQL: debug
  org.hibernate.type: info

decorator:
  datasource:
    p6spy:
      enable-logging: true

