spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect : org.hibernate.dialect.MySQLDialect
  datasource:
    url: ENC(kgK9/mdi4kgWtrLXbxIJByGetfhtr5EzpiKYTGMOTIz4Xl+IFbWdPFK4wrNyrb83SCRqk30I9vvvgPHG2DYGCmJoakcvBREnK5zdeSEIH53f43cRRVmxtTsFgCeBRgYI3hJr5WQJOX0=)
    username: ENC(jIrlODxxlnLjfjNGJWxcK7PlWl42HFmU)
    password: ENC(WcCj7bRbz1ZnW/KZr24eB1jEu5fXjmSSEkuV2/h9ZKw=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode : never
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
  elasticsearch:
    uris: ENC(BX2daQqdGHc4gnij1preYWVeixI3QvYTcMbX8baPTlpPeBMefncMhA==)
    username: ENC(YnhWogbED6K9UWjN7DTD3w==)
    password:  ENC(KUA2cnFAL3Z0YWdc2MFW1dUInWo8u+bxE/k5CjBRT+9waIQD9FeIig==)
  data:
    elasticsearch:
      repositories:
        enabled: true
  cache:
    redis:
      host: ENC(Al1pxd7HCDLTU9kUy9AReg==)
      port: ENC(j3Vu597hs7d4/L/I9xrObw==)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(GoXmhnlYhTWXrVx550csmitTvIcQWnfoqSorlY2jWfk=)
    password: ENC(dXbTFoOHJHLNxADWJ26ejY77pDpr0E/B3CYtujkuV7g=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: ENC(xUQajnpokjuZq6SkK/+p3PbfgNQM/yxwqAb/jU3aPZk=)
      secret-key: ENC(FJ9UEHzhaVXzPeI0D4Ja99GYuFy4/riHuu9+S/e1zqgOS1ZmxsEf7j3OMFcSit1yhhAPvuw/4vA=)
    s3:
      bucket: ENC(HUCZanm+kg08GwIHJ9fzr1bHr6M0skCGAZJgRXGSPC4=)
      path:
        root: ENC(eBnxQq5PqbXeyZ73q30lhL40qXHlr46R5XbHnfgzZM+7NU6LQxoMevHgOP37yWp+)
  cdn:
    path:
      root: ENC(VzfXK3IN7tLoueO7y0qdFvjl1CYogxmul6Dvd2uOnSq9x4Yie3FOUQk3xGbZLKLM)
  image:
    path:
      user: dev/user
      plant : plant
      greenroom : dev/greenroom
temp:
  filePath: src/main/resources/
logging.level:
  org.hibernate.type: info
decorator:
  datasource:
    p6spy:
      enable-logging: true

